{
    "customProperties":{
        "formComponent":false,
        "methods":{
            "onShowMethodID":{
                "arguments":null,
                "parameters":null
            }
        },
        "useCssPosition":true
    },
    "dataSource":"db:/assetflowdb/assignments",
    "encapsulation":108,
    "extendsID":"AFA5CA9E-5A11-4890-8078-856B7A9F3A7C",
    "items":[
        {
            "cssPosition":"380,-1,-1,35,172,30",
            "extendsID":"A65F1FE5-F3BA-4C6A-AA83-8E1519921DE1",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"35",
                    "right":"-1",
                    "top":"380",
                    "width":"172"
                },
                "text":"Assignments List"
            },
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"0643C5EE-69A8-4486-8545-88EE0D614BEA"
        },
        {
            "cssPosition":"45,-1,-1,634,537,318",
            "json":{
                "columns":[
                    {
                        "dataprovider":"assignments_to_employees.name",
                        "headerStyleClass":"bg-tertiary",
                        "headerText":"Employee Name",
                        "id":"assignments_to_employees.name",
                        "styleClassDataprovider":null,
                        "svyUUID":"055C12BE-445D-498F-A7B5-CDD6B98E0CA5"
                    },
                    {
                        "dataprovider":"assignments_to_employees.TotalAssignments",
                        "headerStyleClass":"bg-tertiary",
                        "headerText":"Assignments Number ",
                        "id":"assignments_to_employees.TotalAssignments",
                        "styleClassDataprovider":null,
                        "svyUUID":"0615770A-53C9-46F2-8D90-19B25AE3784B"
                    }
                ],
                "cssPosition":{
                    "bottom":"-1",
                    "height":"318",
                    "left":"634",
                    "right":"-1",
                    "top":"45",
                    "width":"537"
                },
                "pageSize":10
            },
            "name":"table_6",
            "typeName":"servoyextra-table",
            "typeid":47,
            "uuid":"5F7FA185-5514-40BD-B25A-365F451777FF"
        },
        {
            "cssPosition":"422,-1,-1,16,1243,227",
            "extendsID":"8DC2F826-3E8A-479E-8021-C623721EB0FD",
            "json":{
                "columns":[
                    {
                        "dataprovider":"assignments_to_employees.name",
                        "id":"assignments_to_employees.name",
                        "styleClassDataprovider":null,
                        "svyUUID":"750EC25A-D2F2-4719-B4E2-FD0750ECE7EE"
                    },
                    {
                        "dataprovider":"asset_id",
                        "id":"asset_id",
                        "styleClassDataprovider":null,
                        "svyUUID":"6EB9C930-655B-4BEF-9575-F30B9FB22865"
                    },
                    {
                        "dataprovider":"assigned_date",
                        "id":"assigned_date",
                        "styleClassDataprovider":null,
                        "svyUUID":"D22B427F-D1DF-449F-915B-04480CE1FD01"
                    },
                    {
                        "dataprovider":"assignments_to_assets.status",
                        "id":"assignments_to_assets.status",
                        "styleClassDataprovider":null,
                        "svyUUID":"840EE6E6-A5F9-4C18-A41F-229BFD54A780"
                    },
                    {
                        "dataprovider":"assignments_to_assets.category",
                        "id":"assignments_to_assets.category",
                        "styleClassDataprovider":null,
                        "svyUUID":"BE89EDEA-9943-4D20-B74B-C1660F841F00"
                    }
                ],
                "cssPosition":{
                    "bottom":"-1",
                    "height":"227",
                    "left":"16",
                    "right":"-1",
                    "top":"422",
                    "width":"1243"
                }
            },
            "typeName":"aggrid-groupingtable",
            "typeid":47,
            "uuid":"71AA4CDA-99ED-4D7F-A1E7-4A5221E45F08"
        },
        {
            "extendsID":"6C99D024-975B-4AB3-9A51-15F4A52545BE",
            "height":651,
            "typeid":19,
            "uuid":"9240778B-C1B4-4FBB-86C7-75A1A06ABBBB"
        },
        {
            "cssPosition":"15,-1,-1,22,275,30",
            "extendsID":"721B1C70-6EC2-48B6-89AE-91E37FCBAA91",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"22",
                    "right":"-1",
                    "top":"15",
                    "width":"275"
                },
                "text":"Assignments Stats %"
            },
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"94A2E6E3-C9E2-4313-85E0-1767A355A7DF"
        },
        {
            "cssPosition":"45,-1,-1,41,495,321",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"321",
                    "left":"41",
                    "right":"-1",
                    "top":"45",
                    "width":"495"
                }
            },
            "name":"chart_assignments",
            "typeName":"svychartjs-chart",
            "typeid":47,
            "uuid":"A0135ADE-5FC1-4D58-8C6A-138F9B02C64C"
        },
        {
            "cssPosition":"382,-1,-1,969,154,26",
            "extendsID":"1C83FC78-1409-4647-B30F-4E5A638A42E7",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"26",
                    "left":"969",
                    "right":"-1",
                    "top":"382",
                    "width":"154"
                },
                "text":" + Add Assignement"
            },
            "typeName":"bootstrapcomponents-button",
            "typeid":47,
            "uuid":"CA69FEE1-5E4B-4A35-87EA-230845F57F4A"
        }
    ],
    "name":"sub_assignments",
    "navigatorID":"-1",
    "onShowMethodID":"78CEFE94-3392-4570-97B5-2903499DE3B8",
    "showInMenu":true,
    "size":"1153,651",
    "typeid":3,
    "uuid":"98F5A00E-1886-458E-A660-FF900C1DFAA5"
}