{
    "customProperties":{
        "formComponent":false,
        "useCssPosition":true
    },
    "dataSource":"db:/assetflowdb/employees",
    "encapsulation":108,
    "extendsID":"AFA5CA9E-5A11-4890-8078-856B7A9F3A7C",
    "items":[
        {
            "cssPosition":"350,-1,-1,29,820,33",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"33",
                    "left":"29",
                    "right":"-1",
                    "top":"350",
                    "width":"820"
                },
                "dataProviderID":"searchTerm",
                "maxLength":30,
                "onActionMethodID":"249144F6-6899-4C0F-86BD-FF259DF459CD",
                "onDataChangeMethodID":"249144F6-6899-4C0F-86BD-FF259DF459CD",
                "placeholderText":"Search here",
                "styleClass":"form-control-clean"
            },
            "name":"textarea_29",
            "styleClass":"form-control-clean",
            "typeName":"bootstrapcomponents-textbox",
            "typeid":47,
            "uuid":"08FC4609-D554-4992-96B1-B9E375C0085F"
        },
        {
            "cssPosition":"15,-1,-1,22,275,30",
            "extendsID":"721B1C70-6EC2-48B6-89AE-91E37FCBAA91",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"22",
                    "right":"-1",
                    "top":"15",
                    "width":"275"
                },
                "text":"Total Asset By Employee"
            },
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"2A1D4A1C-DF7F-42AF-8EEE-B5DC53A17AAC"
        },
        {
            "extendsID":"6C99D024-975B-4AB3-9A51-15F4A52545BE",
            "height":658,
            "typeid":19,
            "uuid":"910944EA-5D0A-4C49-85DE-06935847E9E6"
        },
        {
            "cssPosition":"350,-1,-1,974,138,32",
            "extendsID":"1C83FC78-1409-4647-B30F-4E5A638A42E7",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"32",
                    "left":"974",
                    "right":"-1",
                    "top":"350",
                    "width":"138"
                },
                "text":" + Add Employee"
            },
            "typeName":"bootstrapcomponents-button",
            "typeid":47,
            "uuid":"974E0808-A0C5-43FE-8863-FDEFE89003A5"
        },
        {
            "cssPosition":"404,-1,-1,34,1211,277",
            "customProperties":{
                "methods":{
                    "onCellClick":{
                        "arguments":null,
                        "parameters":null
                    }
                }
            },
            "extendsID":"8DC2F826-3E8A-479E-8021-C623721EB0FD",
            "json":{
                "columns":[
                    {
                        "dataprovider":"email",
                        "id":"email",
                        "styleClassDataprovider":null,
                        "svyUUID":"7133E415-CDBB-4D2B-81E3-FD90198036B6"
                    },
                    {
                        "dataprovider":"name",
                        "id":"name",
                        "styleClassDataprovider":null,
                        "svyUUID":"B86BFEBC-1CF1-4D18-A56B-EE2347D27848"
                    },
                    {
                        "id":"possessions_col",
                        "styleClass":"fa fa-box text-info",
                        "svyUUID":"240EEFE6-CF34-408A-9461-D2FEB57F4849"
                    },
                    {
                        "id":"delete_col",
                        "styleClass":"fa fa-trash text-danger",
                        "svyUUID":"5EB12E35-6121-428B-B82F-FAFB39B0F2BF"
                    }
                ],
                "cssPosition":{
                    "bottom":"-1",
                    "height":"277",
                    "left":"34",
                    "right":"-1",
                    "top":"404",
                    "width":"1211"
                },
                "onCellClick":"79112E84-10A7-4CBF-A4CA-FAAA0B45B185"
            },
            "typeName":"aggrid-groupingtable",
            "typeid":47,
            "uuid":"C0184CF0-EE54-43BB-8F26-044E7CDC49F3"
        },
        {
            "cssPosition":"56,-1,-1,43,1047,248",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"248",
                    "left":"43",
                    "right":"-1",
                    "top":"56",
                    "width":"1047"
                },
                "foundset":{
                    "dataproviders":{
                        "label":"name",
                        "value":"TotalAssignments"
                    },
                    "foundsetSelector":"db:/assetflowdb/employees",
                    "loadAllRecords":"true"
                },
                "legendLabel":"TotalAssignments",
                "onChartDrawn":null,
                "type":"line"
            },
            "name":"chart_assets",
            "typeName":"svychartjs-chart",
            "typeid":47,
            "uuid":"CDAD05E6-D8A4-4341-A06B-4A4D40206AB3"
        },
        {
            "cssPosition":"314,-1,-1,25,172,30",
            "extendsID":"A65F1FE5-F3BA-4C6A-AA83-8E1519921DE1",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"25",
                    "right":"-1",
                    "top":"314",
                    "width":"172"
                },
                "text":"Employees List"
            },
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"CF9AD352-2B04-4C34-B518-EBED9C590BCB"
        },
        {
            "cssPosition":"349,-1,-1,860,99,34",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"34",
                    "left":"860",
                    "right":"-1",
                    "top":"349",
                    "width":"99"
                },
                "onActionMethodID":"249144F6-6899-4C0F-86BD-FF259DF459CD",
                "styleClass":"btn btn-default btn-success font-weight-bold",
                "text":"Search"
            },
            "name":"button_27_copy424",
            "styleClass":"btn btn-default btn-success font-weight-bold",
            "typeName":"bootstrapcomponents-button",
            "typeid":47,
            "uuid":"D0297EF0-B17F-4CD2-9A57-C1A6674EC3DC"
        }
    ],
    "name":"sub_employees",
    "navigatorID":"-1",
    "onShowMethodID":"-1",
    "showInMenu":true,
    "size":"1139,480",
    "typeid":3,
    "uuid":"9739279F-1607-4301-9FE2-69D9B310B78F"
}