{
    "customProperties":{
        "formComponent":false,
        "methods":{
            "onHideMethodID":{
                "arguments":null,
                "parameters":null
            }
        },
        "useCssPosition":true
    },
    "dataSource":"db:/assetflowdb/assets",
    "encapsulation":108,
    "extendsID":"9918C760-5D75-466C-AE3C-4BE2601602DF",
    "items":[
        {
            "cssPosition":"72,-1,-1,150,175,30",
            "enabled":false,
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"150",
                    "right":"-1",
                    "top":"72",
                    "width":"175"
                },
                "dataProviderID":"category",
                "enabled":false,
                "styleClass":"form-control-clean"
            },
            "name":"textbox_4_copy365",
            "styleClass":"form-control-clean",
            "typeName":"bootstrapcomponents-textbox",
            "typeid":47,
            "uuid":"2699EB7E-6F87-4845-A3D2-D118A281929A"
        },
        {
            "cssPosition":"31,-1,-1,55,112,30",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"55",
                    "right":"-1",
                    "top":"31",
                    "width":"112"
                },
                "styleClass":"text-primary",
                "text":"Tag Number :"
            },
            "name":"label_1",
            "styleClass":"text-primary",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"36B5A2A0-206A-4DE5-8BCE-507973AD2A89"
        },
        {
            "cssPosition":"27,-1,-1,151,175,30",
            "enabled":false,
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"151",
                    "right":"-1",
                    "top":"27",
                    "width":"175"
                },
                "dataProviderID":"tag_number",
                "enabled":false,
                "styleClass":"form-control-clean"
            },
            "name":"textbox_4",
            "styleClass":"form-control-clean",
            "typeName":"bootstrapcomponents-textbox",
            "typeid":47,
            "uuid":"7B80BBDD-B422-43FB-A08C-6F617524147E"
        },
        {
            "cssPosition":"160,-1,-1,150,178,30",
            "enabled":false,
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"150",
                    "right":"-1",
                    "top":"160",
                    "width":"178"
                },
                "dataProviderID":"cost",
                "enabled":false,
                "selectOnEnter":true,
                "styleClass":"form-control-clean"
            },
            "name":"textbox_6",
            "styleClass":"form-control-clean",
            "typeName":"bootstrapcomponents-textbox",
            "typeid":47,
            "uuid":"80AE15A6-1A98-4AAB-8C02-BD09E610FC57"
        },
        {
            "cssPosition":"76,-1,-1,56,114,30",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"56",
                    "right":"-1",
                    "top":"76",
                    "width":"114"
                },
                "styleClass":"text-primary",
                "text":"Category :"
            },
            "name":"label_1_copy823",
            "styleClass":"text-primary",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"8674532A-969E-4A51-B152-F2C9898B1DE9"
        },
        {
            "cssPosition":"162,-1,-1,56,112,30",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"56",
                    "right":"-1",
                    "top":"162",
                    "width":"112"
                },
                "styleClass":"text-primary",
                "text":"Total Seats :"
            },
            "name":"label_3",
            "styleClass":"text-primary",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"8754751D-1DB6-45DA-85A1-DBBB8E97CC78"
        },
        {
            "cssPosition":"120,-1,-1,56,112,30",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"56",
                    "right":"-1",
                    "top":"120",
                    "width":"112"
                },
                "styleClass":"text-primary",
                "text":"Cost :"
            },
            "name":"label_2",
            "styleClass":"text-primary",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"B6C06F76-8D57-47D5-A3A4-48922AB80B17"
        },
        {
            "cssPosition":"116,-1,-1,150,177,30",
            "enabled":false,
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"150",
                    "right":"-1",
                    "top":"116",
                    "width":"177"
                },
                "dataProviderID":"cost",
                "enabled":false,
                "styleClass":"form-control-clean"
            },
            "name":"textbox_5",
            "styleClass":"form-control-clean",
            "typeName":"bootstrapcomponents-textbox",
            "typeid":47,
            "uuid":"D3BAE346-53A5-4587-AD37-225B6CA6C708"
        },
        {
            "cssPosition":"219,-1,-1,201,126,30",
            "customProperties":{
                "methods":{
                    "onActionMethodID":{
                        "arguments":null,
                        "parameters":null
                    }
                }
            },
            "extendsID":"E37D6A7B-81D6-4CF8-807A-93A8B2EA0911",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"201",
                    "right":"-1",
                    "top":"219",
                    "width":"126"
                },
                "onActionMethodID":"67ADDAA4-9B7F-46F9-A1D3-42BF3C7319FB"
            },
            "typeName":"bootstrapcomponents-button",
            "typeid":47,
            "uuid":"F84D19FA-08BD-454F-9F56-C9E23EBB2C06"
        }
    ],
    "name":"sub_assetDetails",
    "navigatorID":"-1",
    "onHideMethodID":"7838DCD2-571D-4F8F-BAB0-2D7D534C9D44",
    "showInMenu":true,
    "typeid":3,
    "uuid":"9378AF18-059F-47B8-B8C4-CA4EC7958E28"
}