{
    "customProperties":{
        "formComponent":false,
        "methods":{
            "onShowMethodID":{
                "arguments":null,
                "parameters":null
            }
        },
        "useCssPosition":true
    },
    "dataSource":"db:/assetflowdb/assets",
    "encapsulation":108,
    "extendsID":"AFA5CA9E-5A11-4890-8078-856B7A9F3A7C",
    "items":[
        {
            "cssPosition":"278,-1,-1,1104,105,27",
            "extendsID":"1C83FC78-1409-4647-B30F-4E5A638A42E7",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"27",
                    "left":"1104",
                    "right":"-1",
                    "top":"278",
                    "width":"105"
                },
                "text":" + Add Asset"
            },
            "typeName":"bootstrapcomponents-button",
            "typeid":47,
            "uuid":"1A1BCB47-86AA-4C09-9F43-AE8A8B4159CC"
        },
        {
            "cssPosition":"42,-1,-1,26,607,229",
            "json":{
                "backgroundColorDataprovider":null,
                "cssPosition":{
                    "bottom":"-1",
                    "height":"229",
                    "left":"26",
                    "right":"-1",
                    "top":"42",
                    "width":"607"
                },
                "labelDataprovider":"status",
                "type":"doughnut",
                "valueDataprovider":"cnt"
            },
            "name":"chart_status",
            "typeName":"svychartjs-chart",
            "typeid":47,
            "uuid":"35F95E83-781A-4A58-8988-2ABF28FDAFEA"
        },
        {
            "cssPosition":"278,-1,-1,39,172,30",
            "extendsID":"A65F1FE5-F3BA-4C6A-AA83-8E1519921DE1",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"39",
                    "right":"-1",
                    "top":"278",
                    "width":"172"
                },
                "text":"Company Assets"
            },
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"95B4E1E5-4884-4631-8B17-E648799C4F7C"
        },
        {
            "cssPosition":"37,-1,-1,681,568,225",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"225",
                    "left":"681",
                    "right":"-1",
                    "top":"37",
                    "width":"568"
                },
                "type":"bar"
            },
            "name":"chart_cost",
            "typeName":"svychartjs-chart",
            "typeid":47,
            "uuid":"AB726675-4944-4582-A970-01C84EA829CB"
        },
        {
            "cssPosition":"330,-1,-1,20,1233,389",
            "customProperties":{
                "methods":{
                    "onCellClick":{
                        "arguments":null,
                        "parameters":null
                    }
                }
            },
            "extendsID":"8DC2F826-3E8A-479E-8021-C623721EB0FD",
            "json":{
                "columns":[
                    {
                        "dataprovider":"name",
                        "id":"name",
                        "styleClassDataprovider":null,
                        "svyUUID":"E84AEDAF-0B5B-49F0-AED6-EB35785932F4"
                    },
                    {
                        "dataprovider":"tag_number",
                        "id":"tag_number",
                        "styleClassDataprovider":null,
                        "svyUUID":"BE7ECEB8-31A2-4BA3-A2CB-589D44B0B62C"
                    },
                    {
                        "dataprovider":"category",
                        "id":"category",
                        "styleClassDataprovider":null,
                        "svyUUID":"918C22A7-3361-495F-B9EE-95732AE1345F"
                    },
                    {
                        "dataprovider":"type",
                        "id":"type",
                        "styleClassDataprovider":null,
                        "svyUUID":"27CE5101-AB74-49B1-B9A9-6ED666DA0157"
                    },
                    {
                        "dataprovider":"status",
                        "id":"status",
                        "styleClassDataprovider":null,
                        "svyUUID":"065984B4-77BB-4F54-9BFB-EF5DE7AAB31A",
                        "valuelist":"30EC734B-3924-4D35-9D4B-67160593D310"
                    },
                    {
                        "dataprovider":"expiration_date",
                        "id":"expiration_date",
                        "styleClassDataprovider":null,
                        "svyUUID":"9FF6E9FB-17EF-487F-B09B-71FCDB02D478"
                    },
                    {
                        "dataprovider":"purchase_date",
                        "id":"purchase_date",
                        "styleClassDataprovider":null,
                        "svyUUID":"3EEFEF4D-4277-4FCF-B236-D086C326CE8D"
                    },
                    {
                        "id":"assetDetail_col",
                        "styleClass":"fas fa-eye text-primary",
                        "svyUUID":"8DA4D794-681E-4D8A-A456-8C6577BF3041"
                    }
                ],
                "cssPosition":{
                    "bottom":"-1",
                    "height":"389",
                    "left":"20",
                    "right":"-1",
                    "top":"330",
                    "width":"1233"
                },
                "onCellClick":"45D2BBB1-94A7-434A-9102-768CB1B2A118"
            },
            "typeName":"aggrid-groupingtable",
            "typeid":47,
            "uuid":"B364BDE8-7F30-4603-9CB8-7FF1AED3A4CD"
        },
        {
            "cssPosition":"15,-1,-1,22,275,30",
            "extendsID":"721B1C70-6EC2-48B6-89AE-91E37FCBAA91",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"22",
                    "right":"-1",
                    "top":"15",
                    "width":"275"
                },
                "text":"Assets Status %"
            },
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"DC27936C-9C38-4EBE-BA42-D37E5E6D7FA8"
        }
    ],
    "name":"sub_assets",
    "navigatorID":"-1",
    "onShowMethodID":"35834F1E-F181-4CE2-A595-D48B66D73FBB",
    "showInMenu":true,
    "size":"1115,480",
    "typeid":3,
    "uuid":"F195EA2B-6234-4B63-8105-B736E2B97197"
}