{
    "customProperties":{
        "formComponent":false,
        "methods":{
            "onHideMethodID":{
                "arguments":null,
                "parameters":null
            }
        },
        "useCssPosition":true
    },
    "dataSource":"db:/assetflowdb/employees",
    "encapsulation":108,
    "extendsID":"C183B54E-61D7-45A7-A31E-2B117A3D943F",
    "items":[
        {
            "cssPosition":"312,-1,-1,224,93,34",
            "extendsID":"447C2F92-07BE-4DCD-B0E6-17314FA9A3C8",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"34",
                    "left":"224",
                    "right":"-1",
                    "top":"312",
                    "width":"93"
                }
            },
            "typeName":"bootstrapcomponents-button",
            "typeid":47,
            "uuid":"1045FFCD-E2C9-4AD7-8190-F36E733482E0"
        },
        {
            "extendsID":"6C99D024-975B-4AB3-9A51-15F4A52545BE",
            "height":480,
            "typeid":19,
            "uuid":"4E923343-087E-4782-A6F9-7B74B7161CDE"
        },
        {
            "cssPosition":"132,-1,-1,123,232,39",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"39",
                    "left":"123",
                    "right":"-1",
                    "top":"132",
                    "width":"232"
                },
                "dataProviderID":"name",
                "placeholderText":"Enter employee name",
                "styleClass":"form-control-clean"
            },
            "name":"textbox_6",
            "styleClass":"form-control-clean",
            "typeName":"bootstrapcomponents-textbox",
            "typeid":47,
            "uuid":"7245D506-755E-47F6-831D-572D0404AD86"
        },
        {
            "cssPosition":"142,-1,-1,53,102,30",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"53",
                    "right":"-1",
                    "top":"142",
                    "width":"102"
                },
                "styleClass":"text-primary active",
                "text":"Name"
            },
            "name":"label_2_copy992",
            "styleClass":"text-primary active",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"A21E1C24-42C7-4D3D-812B-B8CE21C49493"
        },
        {
            "cssPosition":"74,-1,-1,54,109,32",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"32",
                    "left":"54",
                    "right":"-1",
                    "top":"74",
                    "width":"109"
                },
                "styleClass":"text-primary active",
                "text":"Email"
            },
            "name":"label_2",
            "styleClass":"text-primary active",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"BC4229B5-11EC-4DD7-B729-81054D748326"
        },
        {
            "cssPosition":"311,-1,-1,335,93,35",
            "extendsID":"5EA0E26A-2349-47E5-BEEF-A97A1731DFF0",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"35",
                    "left":"335",
                    "right":"-1",
                    "top":"311",
                    "width":"93"
                }
            },
            "typeName":"bootstrapcomponents-button",
            "typeid":47,
            "uuid":"DB81211D-04FC-49F2-897D-F9CB625E7C64"
        },
        {
            "cssPosition":"68,-1,-1,122,231,38",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"38",
                    "left":"122",
                    "right":"-1",
                    "top":"68",
                    "width":"231"
                },
                "dataProviderID":"email",
                "placeholderText":"Enter employee email",
                "styleClass":"form-control-clean"
            },
            "name":"textbox_5",
            "styleClass":"form-control-clean",
            "typeName":"bootstrapcomponents-textbox",
            "typeid":47,
            "uuid":"E01A029C-0869-4CAA-A0B6-323BC57ED5B4"
        }
    ],
    "name":"sub_addEmployee",
    "navigatorID":"-1",
    "onHideMethodID":"190A611C-3E96-41F4-9A8C-12264A16D0A9",
    "showInMenu":true,
    "typeid":3,
    "uuid":"053FAB06-D560-4CB7-AE09-C316DEC6B212"
}