{
    "customProperties":{
        "formComponent":false,
        "useCssPosition":true
    },
    "dataSource":"db:/assetflowdb/assets",
    "encapsulation":108,
    "extendsID":"D646FA8E-BF70-47EC-953B-B4034215A540",
    "items":[
        {
            "cssPosition":"29,-1,-1,45,80,30",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"45",
                    "right":"-1",
                    "top":"29",
                    "width":"80"
                },
                "styleClass":"active text-primary",
                "text":"Home"
            },
            "name":"label_22",
            "styleClass":"active text-primary",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"0032C224-ED91-4455-B8E4-BA35C48A6770"
        },
        {
            "extendsID":"6C99D024-975B-4AB3-9A51-15F4A52545BE",
            "height":362,
            "typeid":19,
            "uuid":"30002CFB-A4E6-4E3B-93C2-B059729C39C5"
        },
        {
            "cssPosition":"243,-1,-1,34,804,513",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"513",
                    "left":"34",
                    "right":"-1",
                    "top":"243",
                    "width":"804"
                },
                "type":"polarArea"
            },
            "name":"chart_polar",
            "typeName":"svychartjs-chart",
            "typeid":47,
            "uuid":"69E3E4A4-93FC-4E8B-B0F0-59D278C65CCC"
        },
        {
            "cssPosition":"142,-1,-1,497,152,38",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"38",
                    "left":"497",
                    "right":"-1",
                    "top":"142",
                    "width":"152"
                },
                "dataProviderID":"TotalAssetsStock",
                "showAs":"text",
                "styleClass":"default-align h2"
            },
            "name":"datalabel_5_copy817",
            "styleClass":"default-align h2",
            "typeName":"bootstrapcomponents-datalabel",
            "typeid":47,
            "uuid":"8BB46FA1-5FE0-4FBB-8AC4-7700875FC1CB"
        },
        {
            "cssPosition":"72,-1,-1,45,306,144",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"144",
                    "left":"45",
                    "right":"-1",
                    "top":"72",
                    "width":"306"
                },
                "styleClass":"active kpi-big-text bg-green kpi-card kpi-icon kpi-label",
                "text":" Total Asset Value"
            },
            "name":"label_13",
            "styleClass":"active kpi-big-text bg-green kpi-card kpi-icon kpi-label",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"93B18488-CD48-45A6-AB58-E0844838B2C6"
        },
        {
            "cssPosition":"246,-1,-1,570,533,407",
            "json":{
                "columns":[
                    {
                        "dataprovider":"asset_uuid",
                        "id":"asset_uuid",
                        "styleClassDataprovider":null,
                        "svyUUID":"DD17EC51-542A-45F5-9C08-FA164610C2E6"
                    },
                    {
                        "dataprovider":"name",
                        "id":"name",
                        "styleClassDataprovider":null,
                        "svyUUID":"12A1A223-A22C-4719-B245-32A87BDB52DE"
                    },
                    {
                        "dataprovider":"purchase_date",
                        "id":"purchase_date",
                        "styleClassDataprovider":null,
                        "svyUUID":"F7A50117-5C8B-45DB-AF44-ED5B4C4D74D2"
                    },
                    {
                        "dataprovider":"cost",
                        "id":"cost",
                        "styleClassDataprovider":null,
                        "svyUUID":"56EE5F2D-426A-4E9B-BCE3-918761E15B19"
                    }
                ],
                "cssPosition":{
                    "bottom":"-1",
                    "height":"407",
                    "left":"570",
                    "right":"-1",
                    "top":"246",
                    "width":"533"
                }
            },
            "name":"datagrid_16",
            "typeName":"aggrid-groupingtable",
            "typeid":47,
            "uuid":"9A770BD0-D42A-4B4F-B6C6-4330BF940B18"
        },
        {
            "cssPosition":"143,-1,-1,934,100,38",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"38",
                    "left":"934",
                    "right":"-1",
                    "top":"143",
                    "width":"100"
                },
                "dataProviderID":"HardInRepairCount",
                "showAs":"text",
                "styleClass":"default-align h2"
            },
            "name":"datalabel_5_copy817_copy460",
            "styleClass":"default-align h2",
            "typeName":"bootstrapcomponents-datalabel",
            "typeid":47,
            "uuid":"B66C81D3-2BB5-4FA8-8F74-4BFF5FE42945"
        },
        {
            "cssPosition":"72,-1,-1,396,327,142",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"142",
                    "left":"396",
                    "right":"-1",
                    "top":"72",
                    "width":"327"
                },
                "styleClass":"kpi-big-text kpi-card kpi-icon kpi-label bg-blue",
                "text":" Stock Value"
            },
            "name":"label_13_copy824",
            "styleClass":"kpi-big-text kpi-card kpi-icon kpi-label bg-blue",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"DB0CBFFC-04E4-458D-9982-9DB30B40BFA2"
        },
        {
            "cssPosition":"70,-1,-1,773,328,144",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"144",
                    "left":"773",
                    "right":"-1",
                    "top":"70",
                    "width":"328"
                },
                "styleClass":"kpi-big-text kpi-card kpi-icon kpi-label bg-orange",
                "text":"Hardware in Repair"
            },
            "name":"label_13_copy824_copy76",
            "styleClass":"kpi-big-text kpi-card kpi-icon kpi-label bg-orange",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"EA24E2E4-CD10-4C6A-B03B-3F6859C5B4E7"
        },
        {
            "cssPosition":"146,-1,-1,136,147,38",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"38",
                    "left":"136",
                    "right":"-1",
                    "top":"146",
                    "width":"147"
                },
                "dataProviderID":"TotalAssetsValue",
                "showAs":"text",
                "styleClass":"default-align h2"
            },
            "name":"datalabel_5",
            "styleClass":"default-align h2",
            "typeName":"bootstrapcomponents-datalabel",
            "typeid":47,
            "uuid":"EFD87FA0-F95B-4BBA-B21A-A4EF66AC50C7"
        }
    ],
    "name":"sub_home",
    "navigatorID":"-1",
    "onShowMethodID":"1B5DA30D-19AC-4A5F-8351-2A9D08550903",
    "showInMenu":true,
    "size":"1144,480",
    "typeid":3,
    "uuid":"378B0C32-EE4F-42C9-8259-100DE0BD20CA"
}