{
    "customProperties":{
        "formComponent":false,
        "methods":{
            "onHideMethodID":{
                "arguments":null,
                "parameters":null
            }
        },
        "useCssPosition":true
    },
    "dataSource":"db:/assetflowdb/assignments",
    "encapsulation":108,
    "extendsID":"C183B54E-61D7-45A7-A31E-2B117A3D943F",
    "items":[
        {
            "cssPosition":"325,-1,-1,361,93,35",
            "extendsID":"5EA0E26A-2349-47E5-BEEF-A97A1731DFF0",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"35",
                    "left":"361",
                    "right":"-1",
                    "top":"325",
                    "width":"93"
                }
            },
            "typeName":"bootstrapcomponents-button",
            "typeid":47,
            "uuid":"4250A100-284E-49A0-931F-F0B955E4C8EE"
        },
        {
            "cssPosition":"205,-1,-1,63,101,30",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"63",
                    "right":"-1",
                    "top":"205",
                    "width":"101"
                },
                "styleClass":"default-align text-primary",
                "text":"Assigned Date"
            },
            "name":"label_2_copy319",
            "styleClass":"default-align text-primary",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"4781D396-8323-4B09-BB7A-7946AD38530D"
        },
        {
            "cssPosition":"207,-1,-1,180,229,30",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"180",
                    "right":"-1",
                    "top":"207",
                    "width":"229"
                },
                "dataProviderID":"assigned_date",
                "placeholderText":"Enter Assigned Date"
            },
            "name":"calendar_6",
            "typeName":"bootstrapcomponents-calendar",
            "typeid":47,
            "uuid":"574EE2F8-CC4D-43C2-98BF-D5AA4A065D3D"
        },
        {
            "cssPosition":"92,-1,-1,180,225,36",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"36",
                    "left":"180",
                    "right":"-1",
                    "top":"92",
                    "width":"225"
                },
                "dataProviderID":"asset_id",
                "floatLabelText":"Enter Asset Name",
                "valuelistID":"DFC1A481-C20F-4DED-8716-C0A1BD023132"
            },
            "name":"floatlabelcombobox_4",
            "typeName":"bootstrapcomponents-floatlabelcombobox",
            "typeid":47,
            "uuid":"590618A7-501E-45EB-8455-A9F03D1F9C4C"
        },
        {
            "cssPosition":"147,-1,-1,180,227,34",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"34",
                    "left":"180",
                    "right":"-1",
                    "top":"147",
                    "width":"227"
                },
                "dataProviderID":"employee_id",
                "floatLabelText":"Enter Emplyee Name",
                "valuelistID":"2944CC3B-D162-4545-A306-7B4057619873"
            },
            "name":"floatlabelcombobox_8",
            "typeName":"bootstrapcomponents-floatlabelcombobox",
            "typeid":47,
            "uuid":"68D06E84-DDC7-4618-AC4D-5B374E22B7C2"
        },
        {
            "cssPosition":"152,-1,-1,63,97,30",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"63",
                    "right":"-1",
                    "top":"152",
                    "width":"97"
                },
                "styleClass":"default-align text-primary",
                "text":"Employee"
            },
            "name":"label_2_copy746",
            "styleClass":"default-align text-primary",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"93BD9958-02F8-4C64-A856-5DF2446984C3"
        },
        {
            "cssPosition":"326,-1,-1,250,93,34",
            "extendsID":"447C2F92-07BE-4DCD-B0E6-17314FA9A3C8",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"34",
                    "left":"250",
                    "right":"-1",
                    "top":"326",
                    "width":"93"
                }
            },
            "typeName":"bootstrapcomponents-button",
            "typeid":47,
            "uuid":"CC6F9658-51BB-47DF-9D39-9C01AD477655"
        },
        {
            "cssPosition":"95,-1,-1,64,97,30",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"64",
                    "right":"-1",
                    "top":"95",
                    "width":"97"
                },
                "styleClass":"text-primary default-align",
                "text":"Asset"
            },
            "name":"label_2",
            "styleClass":"text-primary default-align",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"F1568B93-AEBA-41BE-8713-5B8B1B497861"
        },
        {
            "extendsID":"6C99D024-975B-4AB3-9A51-15F4A52545BE",
            "height":480,
            "typeid":19,
            "uuid":"FE27359B-CA52-46C2-9421-80658393469A"
        }
    ],
    "name":"sub_addassignments",
    "navigatorID":"-1",
    "onHideMethodID":"190A611C-3E96-41F4-9A8C-12264A16D0A9",
    "showInMenu":true,
    "typeid":3,
    "uuid":"5426D56A-A9E9-4AE3-A0D1-E94338099780"
}