{
    "customProperties":{
        "formComponent":false,
        "methods":{
            "onHideMethodID":{
                "arguments":null,
                "parameters":null
            }
        },
        "useCssPosition":true
    },
    "dataSource":"db:/assetflowdb/assets",
    "encapsulation":108,
    "extendsID":"C183B54E-61D7-45A7-A31E-2B117A3D943F",
    "items":[
        {
            "cssPosition":"94,-1,-1,33,70,32",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"32",
                    "left":"33",
                    "right":"-1",
                    "top":"94",
                    "width":"70"
                },
                "styleClass":"text-primary default-align font-weight-bold h5",
                "text":"Category"
            },
            "name":"label_2",
            "styleClass":"text-primary default-align font-weight-bold h5",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"067AC296-7B34-4D47-B951-7B27ED2256A8"
        },
        {
            "cssPosition":"230,-1,-1,402,169,35",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"35",
                    "left":"402",
                    "right":"-1",
                    "top":"230",
                    "width":"169"
                },
                "dataProviderID":"tag_number",
                "placeholderText":"J78677493",
                "styleClass":"form-control-clean"
            },
            "name":"textbox_6_copy242_copy591",
            "styleClass":"form-control-clean",
            "typeName":"bootstrapcomponents-textbox",
            "typeid":47,
            "uuid":"0B3D3A71-E1BD-4641-B376-8CC7F45769F6"
        },
        {
            "cssPosition":"231,-1,-1,289,84,30",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"289",
                    "right":"-1",
                    "top":"231",
                    "width":"84"
                },
                "styleClass":"text-primary default-align font-weight-bold h5",
                "text":"Tag Number"
            },
            "name":"label_2_copy992_copy783_copy824",
            "styleClass":"text-primary default-align font-weight-bold h5",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"110EAFA0-E1D4-4119-AF32-14BBD6F6E807"
        },
        {
            "cssPosition":"88,-1,-1,292,87,32",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"32",
                    "left":"292",
                    "right":"-1",
                    "top":"88",
                    "width":"87"
                },
                "styleClass":"text-primary default-align font-weight-bold h5",
                "text":"Total Seats"
            },
            "name":"label_2_copy340",
            "styleClass":"text-primary default-align font-weight-bold h5",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"2EF090F8-B508-413C-8E57-7BEA3B8E0406"
        },
        {
            "cssPosition":"39,-1,-1,33,87,32",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"32",
                    "left":"33",
                    "right":"-1",
                    "top":"39",
                    "width":"87"
                },
                "styleClass":"text-primary default-align font-weight-bold h5",
                "text":"Name"
            },
            "name":"label_2_copy874",
            "styleClass":"text-primary default-align font-weight-bold h5",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"2FE365E6-4C4A-429B-900E-D026DE001A52"
        },
        {
            "cssPosition":"84,-1,-1,403,166,35",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"35",
                    "left":"403",
                    "right":"-1",
                    "top":"84",
                    "width":"166"
                },
                "dataProviderID":"total_seats",
                "inputType":"number",
                "placeholderText":"1 - 50",
                "styleClass":"form-control-clean"
            },
            "name":"textbox_5_copy833",
            "styleClass":"form-control-clean",
            "typeName":"bootstrapcomponents-textbox",
            "typeid":47,
            "uuid":"33C45CC4-6B24-4AD7-AB79-E89EB337DE06"
        },
        {
            "cssPosition":"36,-1,-1,101,465,36",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"36",
                    "left":"101",
                    "right":"-1",
                    "top":"36",
                    "width":"465"
                },
                "dataProviderID":"name",
                "placeholderText":"Ex: IntilliJ license",
                "styleClass":"form-control-clean"
            },
            "name":"textbox_5",
            "styleClass":"form-control-clean",
            "typeName":"bootstrapcomponents-textbox",
            "typeid":47,
            "uuid":"3AADB051-D6E4-406E-BA08-9CB31927684C"
        },
        {
            "cssPosition":"159,-1,-1,99,164,35",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"35",
                    "left":"99",
                    "right":"-1",
                    "top":"159",
                    "width":"164"
                },
                "dataProviderID":"type",
                "floatLabelText":"Asset Type",
                "valuelistID":"28FD9DD9-AE1F-4073-AE12-D55B365A892F"
            },
            "name":"floatlabelcombobox_11_copy971",
            "typeName":"bootstrapcomponents-floatlabelcombobox",
            "typeid":47,
            "uuid":"55992FB6-FD48-4D47-A28D-DC37D0927A97"
        },
        {
            "cssPosition":"93,-1,-1,101,164,35",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"35",
                    "left":"101",
                    "right":"-1",
                    "top":"93",
                    "width":"164"
                },
                "dataProviderID":"category",
                "floatLabelText":"Asset Category",
                "valuelistID":"B1E77594-F7A3-4F69-9494-4B4411D0AFC0"
            },
            "name":"floatlabelcombobox_11",
            "typeName":"bootstrapcomponents-floatlabelcombobox",
            "typeid":47,
            "uuid":"69CE4EAF-77C8-4E40-862D-27941E90F4A1"
        },
        {
            "cssPosition":"234,-1,-1,98,166,33",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"33",
                    "left":"98",
                    "right":"-1",
                    "top":"234",
                    "width":"166"
                },
                "dataProviderID":"cost",
                "placeholderText":"Enter Cost $",
                "styleClass":"form-control-clean"
            },
            "name":"textbox_6_copy242_copy605",
            "styleClass":"form-control-clean",
            "typeName":"bootstrapcomponents-textbox",
            "typeid":47,
            "uuid":"6F6E2FFB-DD2E-4640-91FC-553AD5815AA4"
        },
        {
            "cssPosition":"158,-1,-1,291,106,30",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"291",
                    "right":"-1",
                    "top":"158",
                    "width":"106"
                },
                "styleClass":"text-primary default-align font-weight-bold h5",
                "text":"Expiration Date"
            },
            "name":"label_2_copy992_copy783_copy300",
            "styleClass":"text-primary default-align font-weight-bold h5",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"8600BBBB-3451-4698-8BC4-78260D939C50"
        },
        {
            "extendsID":"6C99D024-975B-4AB3-9A51-15F4A52545BE",
            "height":480,
            "typeid":19,
            "uuid":"BFB390E6-1E86-4155-BA8D-F146DB18574F"
        },
        {
            "cssPosition":"153,-1,-1,405,163,35",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"35",
                    "left":"405",
                    "right":"-1",
                    "top":"153",
                    "width":"163"
                },
                "dataProviderID":"expiration_date",
                "floatLabelText":"MM/DD/YY"
            },
            "name":"floatlabelcalendar_14",
            "typeName":"bootstrapcomponents-floatlabelcalendar",
            "typeid":47,
            "uuid":"C0BF7B58-5754-49C5-B7A2-1ED7DD9146F5"
        },
        {
            "cssPosition":"236,-1,-1,39,84,30",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"39",
                    "right":"-1",
                    "top":"236",
                    "width":"84"
                },
                "styleClass":"text-primary font-weight-bold default-align h5",
                "text":"Cost"
            },
            "name":"label_2_copy992_copy783_copy686",
            "styleClass":"text-primary font-weight-bold default-align h5",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"E82B4E6B-D3BB-4E4A-AC51-276E01EFB346"
        },
        {
            "cssPosition":"163,-1,-1,35,80,30",
            "json":{
                "cssPosition":{
                    "bottom":"-1",
                    "height":"30",
                    "left":"35",
                    "right":"-1",
                    "top":"163",
                    "width":"80"
                },
                "styleClass":"text-primary default-align font-weight-bold h5",
                "text":"Type"
            },
            "name":"label_2_copy992",
            "styleClass":"text-primary default-align font-weight-bold h5",
            "typeName":"bootstrapcomponents-label",
            "typeid":47,
            "uuid":"EA863327-4D30-45FB-909C-3287DD083838"
        }
    ],
    "name":"sub_addAssets",
    "navigatorID":"-1",
    "onHideMethodID":"190A611C-3E96-41F4-9A8C-12264A16D0A9",
    "showInMenu":true,
    "typeid":3,
    "uuid":"1F577DFE-1B79-4EC7-8052-DEC2E0FE8E66"
}